FROM python:3.9.21

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 80 443

CMD ["uvicorn", "--host", "0.0.0.0", "--port", "80", "--reload", "src.app:app"]