name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      version:
        description: 'Specify the version of the app to deploy'
        required: true
        default: '1.0.0'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }} environment"

      - name: Deploy the application
        run: |
          # Your deploy script here (e.g., uploading to a server)
          echo "Deploying version ${{ github.event.inputs.version }} to ${ { github.event.inputs.environment }}"
